export type CourseLevel = 'beginner' | 'intermediate' | 'advanced' | 'expert' | 'master';

export interface Course {
    id: number;
    title: string;
    description: string;
    level: CourseLevel;
    tags: string[];
    folder: string;
    duration: string;
}

export const courses: Course[] = [
    // BEGINNER LEVEL (1-20)
    { id: 1, title: "Introduction to AI Agents", description: "Learn what AI agents are, their components, and basic architecture.", level: "beginner", tags: ["basics", "introduction"], folder: "course_001_intro_agents", duration: "1h" },
    { id: 2, title: "Prompt Engineering Fundamentals", description: "Master crafting effective prompts for LLMs with few-shot and chain-of-thought.", level: "beginner", tags: ["prompting", "llm"], folder: "course_002_prompt_engineering", duration: "2h" },
    { id: 3, title: "Simple Chatbot Agent", description: "Build a conversational agent with context awareness and basic memory.", level: "beginner", tags: ["chatbot", "conversation"], folder: "course_003_simple_chatbot", duration: "2h" },
    { id: 4, title: "Agent State Management", description: "Understand how agents maintain state and context across interactions.", level: "beginner", tags: ["state", "context"], folder: "course_004_state_management", duration: "1.5h" },
    { id: 5, title: "Basic Agent Chains", description: "Connect multiple agent operations in sequence to solve complex tasks.", level: "beginner", tags: ["chains", "pipeline"], folder: "course_005_agent_chains", duration: "2h" },
    { id: 6, title: "Text Classification Agent", description: "Build an agent that classifies text into categories with confidence scores.", level: "beginner", tags: ["classification", "nlp"], folder: "course_006_text_classification", duration: "2h" },
    { id: 7, title: "Sentiment Analysis Agent", description: "Create an agent that analyzes sentiment with detailed emotional breakdowns.", level: "beginner", tags: ["sentiment", "emotion"], folder: "course_007_sentiment_analysis", duration: "1.5h" },
    { id: 8, title: "Data Extraction Agent", description: "Extract structured information from unstructured text using LLMs.", level: "beginner", tags: ["extraction", "parsing"], folder: "course_008_data_extraction", duration: "2h" },
    { id: 9, title: "Summarization Agent", description: "Build an agent that creates concise summaries of long documents.", level: "beginner", tags: ["summarization", "text"], folder: "course_009_summarization", duration: "1.5h" },
    { id: 10, title: "Question Answering Agent", description: "Create an agent that answers questions based on provided context.", level: "beginner", tags: ["qa", "retrieval"], folder: "course_010_question_answering", duration: "2h" },
    { id: 11, title: "Translation Agent", description: "Build a multilingual translation agent with quality assessment.", level: "beginner", tags: ["translation", "multilingual"], folder: "course_011_translation", duration: "2h" },
    { id: 12, title: "Code Generation Agent", description: "Create an agent that generates code from natural language descriptions.", level: "beginner", tags: ["code-gen", "programming"], folder: "course_012_code_generation", duration: "2.5h" },
    { id: 13, title: "Agent Logging & Debugging", description: "Learn to track, log, and debug agent behavior effectively.", level: "beginner", tags: ["logging", "debugging"], folder: "course_013_logging_debugging", duration: "1.5h" },
    { id: 14, title: "Agent Error Handling", description: "Implement robust error handling and recovery mechanisms in agents.", level: "beginner", tags: ["errors", "recovery"], folder: "course_014_error_handling", duration: "2h" },
    { id: 15, title: "Agent Performance Metrics", description: "Measure and optimize agent performance with key metrics.", level: "beginner", tags: ["metrics", "performance"], folder: "course_015_performance_metrics", duration: "2h" },
    { id: 16, title: "Simple Tool-Using Agent", description: "Enable agents to use external tools like calculators and APIs.", level: "beginner", tags: ["tools", "apis"], folder: "course_016_tool_using", duration: "2.5h" },
    { id: 17, title: "Agent with Web Search", description: "Build an agent that can search the web for information.", level: "beginner", tags: ["web-search", "retrieval"], folder: "course_017_web_search", duration: "2h" },
    { id: 18, title: "File Processing Agent", description: "Create an agent that processes various file formats (PDF, CSV, JSON).", level: "beginner", tags: ["files", "processing"], folder: "course_018_file_processing", duration: "2h" },
    { id: 19, title: "Agent Configuration Management", description: "Learn to configure agents with parameters and settings.", level: "beginner", tags: ["configuration", "settings"], folder: "course_019_configuration", duration: "1.5h" },
    { id: 20, title: "Basic Agent Testing", description: "Write tests for agents to ensure reliability and correctness.", level: "beginner", tags: ["testing", "quality"], folder: "course_020_testing", duration: "2h" },

    // INTERMEDIATE LEVEL (21-40)
    { id: 21, title: "Vector Embeddings Fundamentals", description: "Understand embeddings and vector representations for semantic search.", level: "intermediate", tags: ["embeddings", "vectors"], folder: "course_021_embeddings", duration: "2h" },
    { id: 22, title: "Vector Database Integration", description: "Store and retrieve embeddings using vector databases.", level: "intermediate", tags: ["vector-db", "storage"], folder: "course_022_vector_database", duration: "2.5h" },
    { id: 23, title: "Basic RAG System", description: "Build a Retrieval-Augmented Generation system for knowledge retrieval.", level: "intermediate", tags: ["rag", "retrieval"], folder: "course_023_basic_rag", duration: "3h" },
    { id: 24, title: "Document Chunking Strategies", description: "Learn optimal strategies (token-based, semantic) for splitting documents.", level: "intermediate", tags: ["chunking", "documents"], folder: "course_024_document_chunking", duration: "2h" },
    { id: 25, title: "Semantic Search Agent", description: "Build an agent that performs semantic search across documents.", level: "intermediate", tags: ["semantic-search", "similarity"], folder: "course_025_semantic_search", duration: "2.5h" },
    { id: 26, title: "Conversational Memory", description: "Implement short-term and long-term memory for conversational agents.", level: "intermediate", tags: ["memory", "conversation"], folder: "course_026_conversational_memory", duration: "2h" },
    { id: 27, title: "Agent with Persistent Storage", description: "Store agent state and memory in databases for persistence.", level: "intermediate", tags: ["persistence", "database"], folder: "course_027_persistent_storage", duration: "2.5h" },
    { id: 28, title: "Multi-Tool Agent", description: "Create agents that can use multiple tools intelligently.", level: "intermediate", tags: ["multi-tool", "orchestration"], folder: "course_028_multi_tool", duration: "3h" },
    { id: 29, title: "API Integration Agent", description: "Build agents that interact with REST APIs and web services.", level: "intermediate", tags: ["api", "integration"], folder: "course_029_api_integration", duration: "2.5h" },
    { id: 30, title: "Eval Driven Development", description: "Use LLM-as-a-Judge to automatically grade and test your agents with unit tests.", level: "intermediate", tags: ["evals", "testing", "llm-judge"], folder: "course_030_eval_driven_dev", duration: "2.5h" },
    { id: 31, title: "E2E Testing (The Simulator)", description: "Build User Simulator Agents to stress-test your system in adversarial conversations.", level: "intermediate", tags: ["simulation", "e2e-testing"], folder: "course_031_e2e_testing", duration: "2.5h" },
    { id: 32, title: "Deployment & Observability", description: "Monitor latency, costs, and traces. Build a production-grade AI Ops dashboard.", level: "intermediate", tags: ["ops", "observability", "deployment"], folder: "course_032_observability", duration: "2.5h" },
    { id: 33, title: "Capstone: Multi-Agent Orchestrator", description: "The Final Project. Build a Head Node that routes tasks to specialized Worker Agents.", level: "advanced", tags: ["orchestration", "multi-agent", "capstone"], folder: "course_033_capstone", duration: "4h" },
    { id: 34, title: "Document QA Agent", description: "\"Chat with your Data\". Build an ephemeral RAG pipeline to answer questions about specific documents with citations.", level: "intermediate", tags: ["document-qa", "rag", "citations"], folder: "course_034_document_qa", duration: "3h" },
    { id: 35, title: "Semantic Routing", description: "Use Vector Embeddings to classify user intent instantly (zero-shot) without using an LLM.", level: "intermediate", tags: ["routing", "vectors", "classification"], folder: "course_035_routing", duration: "2.5h" },
    { id: 36, title: "Streaming Response Agent", description: "Implement real-time token streaming to reduce perceived latency and improve UX.", level: "intermediate", tags: ["streaming", "ux", "real-time"], folder: "course_036_streaming", duration: "2h" },
    { id: 37, title: "Agent Caching Strategies", description: "Implement Semantic Caching to instantly return results for similar questions, saving time and money.", level: "intermediate", tags: ["caching", "vectors", "performance"], folder: "course_037_caching", duration: "2h" },
    { id: 38, title: "Agent Rate Limiting", description: "Protect your agents with a Token Bucket algorithm to throttle usage and prevent abuse.", level: "intermediate", tags: ["rate-limiting", "throttling", "safety"], folder: "course_038_rate_limiting", duration: "2h" },
    { id: 39, title: "Agent Security Basics", description: "The Red Team Lab. Defend against Prompt Injection attacks using system prompt hardening and input guards.", level: "intermediate", tags: ["security", "prompt-injection", "red-teaming"], folder: "course_039_security", duration: "2.5h" },
    { id: 40, title: "Agent Cost Optimization", description: "Visualize token usage and costs in real-time. Learn strategies to reduce your LLM bill.", level: "intermediate", tags: ["cost", "tokens", "fin-ops"], folder: "course_040_cost_optimization", duration: "2h" },

    // ADVANCED LEVEL (41-60)
    { id: 41, title: "Advanced RAG & Self-RAG", description: "Implement the \"CRAG\" pipeline: Retrieve, Rerank, and Correct. Use LLM-as-a-Judge to filter noise.", level: "advanced", tags: ["rag", "reranking", "crag"], folder: "course_041_advanced_rag", duration: "3h" },
    { id: 42, title: "Chain-of-Thought Reasoning", description: "Unlock \"System 2\" thinking. Force the agent to think step-by-step before answering logic puzzles.", level: "advanced", tags: ["reasoning", "cot", "system-2"], folder: "course_042_chain_of_thought", duration: "3h" },
    { id: 43, title: "Tree-of-Thought Agent", description: "Build an agent that explores multiple storylines, evaluates them, and picks the best path forward.", level: "advanced", tags: ["tot", "search", "creative"], folder: "course_043_tree_of_thought", duration: "3.5h" },
    { id: 44, title: "ReAct & Tool Use Patterns", description: "Master the Reasoning + Acting loop. Build an agent that uses tools to solve multi-step problems.", level: "advanced", tags: ["react", "tools", "reasoning"], folder: "course_044_react_pattern", duration: "3h" },
    { id: 45, title: "Self-Reflection Agent", description: "Implement the \"Reflexion\" pattern. An agent that critiques and revises its own work for higher quality.", level: "advanced", tags: ["reflection", "self-improvement"], folder: "course_045_self_reflection", duration: "3h" },
    { id: 46, title: "Multi-Agent Systems (CrewAI Style)", description: "Orchestrate a team of specialized agents (Manager, Researcher, Writer) to collaborate on complex tasks.", level: "advanced", tags: ["multi-agent", "collaboration", "crewai"], folder: "course_046_multi_agent_collab", duration: "4h" },
    { id: 47, title: "Agent Communication Protocols", description: "Design strict JSON schemas for reliable inter-agent communication, avoiding natural language ambiguity.", level: "advanced", tags: ["communication", "interaction", "protocols"], folder: "course_047_communication", duration: "3h" },
    { id: 48, title: "Hierarchical Graphs (LangGraph)", description: "Create hierarchical state machines and supervisors, like LangGraph.", level: "advanced", tags: ["hierarchy", "architecture", "langgraph"], folder: "course_048_hierarchical", duration: "3.5h" },
    { id: 49, title: "Agent Planning & Scheduling", description: "Implement planning algorithms for agents to achieve goals.", level: "advanced", tags: ["planning", "scheduling"], folder: "course_049_planning", duration: "3.5h" },
    { id: 50, title: "Goal-Oriented Agent", description: "Build agents that decompose and achieve complex goals.", level: "advanced", tags: ["goals", "decomposition"], folder: "course_050_goal_oriented", duration: "3h" },
    { id: 51, title: "Agent with Long-Term Memory", description: "Implement sophisticated long-term memory systems for agents.", level: "advanced", tags: ["memory", "long-term"], folder: "course_051_long_term_memory", duration: "3h" },
    { id: 52, title: "Knowledge Graph Agent", description: "Build agents that construct and query knowledge graphs.", level: "advanced", tags: ["knowledge-graph", "graph"], folder: "course_052_knowledge_graph", duration: "4h" },
    { id: 53, title: "Code Execution Agent", description: "Create agents that write and execute code safely in sandboxes.", level: "advanced", tags: ["code-execution", "sandbox"], folder: "course_053_code_execution", duration: "3.5h" },
    { id: 54, title: "Research Assistant Agent", description: "Build an agent that conducts research and synthesizes information.", level: "advanced", tags: ["research", "synthesis"], folder: "course_054_research_assistant", duration: "4h" },
    { id: 55, title: "Debate & Argumentation Agent", description: "Create agents that can debate and construct logical arguments.", level: "advanced", tags: ["debate", "argumentation"], folder: "course_055_debate", duration: "3h" },
    { id: 56, title: "Creative Writing Agent", description: "Build agents that generate creative content with style control.", level: "advanced", tags: ["creative", "writing"], folder: "course_056_creative_writing", duration: "3h" },
    { id: 57, title: "Agent Fine-Tuning", description: "Fine-tune LLMs for specialized agent behaviors.", level: "advanced", tags: ["fine-tuning", "training"], folder: "course_057_fine_tuning", duration: "4h" },
    { id: 58, title: "Agent Evaluation Framework", description: "Build comprehensive evaluation systems for agent performance.", level: "advanced", tags: ["evaluation", "testing"], folder: "course_058_evaluation", duration: "3h" },
    { id: 59, title: "Agent A/B Testing", description: "Implement A/B testing frameworks for comparing agent versions.", level: "advanced", tags: ["ab-testing", "comparison"], folder: "course_059_ab_testing", duration: "3h" },
    { id: 60, title: "Agent Observability (AgentOps)", description: "Implement tracing and monitoring using AgentOps principles.", level: "advanced", tags: ["observability", "monitoring", "agentops"], folder: "course_060_observability", duration: "3h" },

    // EXPERT LEVEL (61-80)
    { id: 61, title: "Autonomous Task Agent", description: "Build fully autonomous agents that complete tasks without human intervention.", level: "expert", tags: ["autonomous", "automation"], folder: "course_061_autonomous_task", duration: "4h" },
    { id: 62, title: "Agent with Continuous Learning", description: "Implement agents that learn and improve from interactions.", level: "expert", tags: ["learning", "improvement"], folder: "course_062_continuous_learning", duration: "4h" },
    { id: 63, title: "Reinforcement Learning Agent", description: "Apply RL techniques to optimize agent decision-making.", level: "expert", tags: ["rl", "optimization"], folder: "course_063_rl_agent", duration: "5h" },
    { id: 64, title: "Agent Swarms (AutoGen Patterns)", description: "Create conversational swarms and group chats, inspired by AutoGen.", level: "expert", tags: ["swarm", "emergence", "autogen"], folder: "course_064_swarm", duration: "4h" },
    { id: 65, title: "Adversarial Agent Training", description: "Train agents through adversarial interactions for robustness.", level: "expert", tags: ["adversarial", "robustness"], folder: "course_065_adversarial", duration: "4h" },
    { id: 66, title: "Agent Meta-Learning", description: "Build agents that learn how to learn new tasks quickly.", level: "expert", tags: ["meta-learning", "adaptation"], folder: "course_066_meta_learning", duration: "4.5h" },
    { id: 67, title: "Multi-Modal Agent", description: "Create agents that process text, images, audio, and video.", level: "expert", tags: ["multi-modal", "vision"], folder: "course_067_multi_modal", duration: "4h" },
    { id: 68, title: "Agent with Computer Vision", description: "Build agents that understand and reason about visual information.", level: "expert", tags: ["vision", "images"], folder: "course_068_computer_vision", duration: "4h" },
    { id: 69, title: "Voice-Enabled Agent", description: "Create agents with speech recognition and synthesis capabilities.", level: "expert", tags: ["voice", "speech"], folder: "course_069_voice_agent", duration: "4h" },
    { id: 70, title: "Agent Workflow Automation", description: "Build agents that automate complex business workflows.", level: "expert", tags: ["workflow", "automation"], folder: "course_070_workflow_automation", duration: "4.5h" },
    { id: 71, title: "Agent Orchestration Platform", description: "Create platforms for managing and orchestrating multiple agents.", level: "expert", tags: ["platform", "orchestration"], folder: "course_071_orchestration_platform", duration: "5h" },
    { id: 72, title: "Agent Marketplace System", description: "Build systems for discovering, sharing, and deploying agents.", level: "expert", tags: ["marketplace", "sharing"], folder: "course_072_marketplace", duration: "4h" },
    { id: 73, title: "Agent Version Control", description: "Implement version control and rollback for agent systems.", level: "expert", tags: ["version-control", "rollback"], folder: "course_073_version_control", duration: "3.5h" },
    { id: 74, title: "Agent Load Balancing", description: "Distribute agent workloads across multiple instances efficiently.", level: "expert", tags: ["load-balancing", "scaling"], folder: "course_074_load_balancing", duration: "4h" },
    { id: 75, title: "Agent Fault Tolerance", description: "Build resilient agents that handle failures gracefully.", level: "expert", tags: ["fault-tolerance", "resilience"], folder: "course_075_fault_tolerance", duration: "4h" },
    { id: 76, title: "Agent Security Hardening", description: "Implement advanced security measures for production agents.", level: "expert", tags: ["security", "hardening"], folder: "course_076_security_hardening", duration: "4h" },
    { id: 77, title: "Agent Privacy & Compliance", description: "Ensure agents comply with privacy regulations (GDPR, CCPA).", level: "expert", tags: ["privacy", "compliance"], folder: "course_077_privacy_compliance", duration: "4h" },
    { id: 78, title: "Agent Explainability", description: "Make agent decisions transparent and explainable.", level: "expert", tags: ["explainability", "transparency"], folder: "course_078_explainability", duration: "4h" },
    { id: 79, title: "Agent Bias Detection", description: "Detect and mitigate biases in agent behavior.", level: "expert", tags: ["bias", "fairness"], folder: "course_079_bias_detection", duration: "4h" },
    { id: 80, title: "Agent Performance Tuning", description: "Advanced techniques for optimizing agent latency and throughput.", level: "expert", tags: ["performance", "optimization"], folder: "course_080_performance_tuning", duration: "4h" },

    // MASTER LEVEL (81-100)
    { id: 81, title: "Production Agent Deployment", description: "Deploy agents to production with CI/CD pipelines.", level: "master", tags: ["deployment", "production"], folder: "course_081_production_deployment", duration: "5h" },
    { id: 82, title: "Agent Microservices Architecture", description: "Design agent systems using microservices patterns.", level: "master", tags: ["microservices", "architecture"], folder: "course_082_microservices", duration: "5h" },
    { id: 83, title: "Agent Event-Driven Architecture", description: "Build event-driven agent systems with message queues.", level: "master", tags: ["event-driven", "messaging"], folder: "course_083_event_driven", duration: "5h" },
    { id: 84, title: "Agent Distributed Systems", description: "Create distributed agent systems across multiple nodes.", level: "master", tags: ["distributed", "scaling"], folder: "course_084_distributed", duration: "5h" },
    { id: 85, title: "Agent Kubernetes Deployment", description: "Deploy and manage agents on Kubernetes clusters.", level: "master", tags: ["kubernetes", "containers"], folder: "course_085_kubernetes", duration: "5h" },
    { id: 86, title: "Agent Serverless Architecture", description: "Build serverless agent systems with AWS Lambda, Azure Functions.", level: "master", tags: ["serverless", "cloud"], folder: "course_086_serverless", duration: "4.5h" },
    { id: 87, title: "Agent Edge Computing", description: "Deploy agents on edge devices for low-latency applications.", level: "master", tags: ["edge", "iot"], folder: "course_087_edge_computing", duration: "5h" },
    { id: 88, title: "Agent Federated Learning", description: "Train agents across distributed data sources while preserving privacy.", level: "master", tags: ["federated", "privacy"], folder: "course_088_federated_learning", duration: "5h" },
    { id: 89, title: "Constitutional AI & Guardrails", description: "Implement safety guidelines and guardrails for aligned agents.", level: "master", tags: ["constitutional", "safety", "guardrails"], folder: "course_089_constitutional_ai", duration: "5h" },
    { id: 90, title: "Agent RLHF Implementation", description: "Use Reinforcement Learning from Human Feedback to improve agents.", level: "master", tags: ["rlhf", "feedback"], folder: "course_090_rlhf", duration: "5h" },
    { id: 91, title: "Agent Prompt Optimization", description: "Automatically optimize prompts using gradient-based methods.", level: "master", tags: ["prompt-optimization", "automation"], folder: "course_091_prompt_optimization", duration: "4.5h" },
    { id: 92, title: "Agent Mixture of Experts", description: "Build agent systems using mixture of experts architecture.", level: "master", tags: ["moe", "experts"], folder: "course_092_mixture_experts", duration: "5h" },
    { id: 93, title: "Agent Retrieval Optimization", description: "Advanced techniques for optimizing retrieval in RAG systems.", level: "master", tags: ["retrieval", "optimization"], folder: "course_093_retrieval_optimization", duration: "5h" },
    { id: 94, title: "Agent Causal Reasoning", description: "Implement causal reasoning capabilities in agents.", level: "master", tags: ["causal", "reasoning"], folder: "course_094_causal_reasoning", duration: "5h" },
    { id: 95, title: "Agent Symbolic Integration", description: "Combine neural and symbolic AI in hybrid agent systems.", level: "master", tags: ["symbolic", "hybrid"], folder: "course_095_symbolic_integration", duration: "5h" },
    { id: 96, title: "Agent World Models", description: "Build agents with internal world models for planning.", level: "master", tags: ["world-models", "simulation"], folder: "course_096_world_models", duration: "5h" },
    { id: 97, title: "Agent Emergent Abilities", description: "Study and leverage emergent abilities in large language models.", level: "master", tags: ["emergent", "abilities"], folder: "course_097_emergent_abilities", duration: "5h" },
    { id: 98, title: "Agent Scaling Laws", description: "Understand and apply scaling laws for agent systems.", level: "master", tags: ["scaling", "laws"], folder: "course_098_scaling_laws", duration: "5h" },
    { id: 99, title: "Agent Research Frontiers", description: "Explore cutting-edge research in agentic AI systems.", level: "master", tags: ["research", "frontiers"], folder: "course_099_research_frontiers", duration: "5h" },
    { id: 100, title: "Building Your Own Agent Framework", description: "Design and implement a complete agent framework from scratch.", level: "master", tags: ["framework", "architecture"], folder: "course_100_own_framework", duration: "6h" }
];
