'use server';

export interface ProtocolLog {
    type: 'unstructured' | 'structured';
    sender: 'User' | 'PizzaBot';
    message: string;
    status: 'success' | 'failure';
    error?: string;
}

// --- Simulating the Problem ---

export async function sendUnstructured(input: string): Promise<ProtocolLog[]> {
    const logs: ProtocolLog[] = [];
    logs.push({ type: 'unstructured', sender: 'User', message: input, status: 'success' });

    // Naive bot trying to regex parsing natural language
    if (input.includes("pepperoni") && input.includes("large")) {
        logs.push({ type: 'unstructured', sender: 'PizzaBot', message: "Ordered large pepperoni.", status: 'success' });
    } else {
        logs.push({
            type: 'unstructured',
            sender: 'PizzaBot',
            message: "I didn't understand. What size? Toppings?",
            status: 'failure',
            error: "AmbiguityError"
        });
    }
    return logs;
}

// --- Simulating the Solution (Protocol) ---

export async function sendStructured(input: string): Promise<ProtocolLog[]> {
    const logs: ProtocolLog[] = [];

    // Ideally this input is generated by an LLM strictly adhering to schema
    // meaningful Input: '{"action": "order", "item": "pizza", "params": {"size": "large", "topping": "pepperoni"}}'

    logs.push({ type: 'structured', sender: 'User', message: input, status: 'success' });

    try {
        const payload = JSON.parse(input);

        // Protocol Validation
        if (payload.action === 'order' && payload.item === 'pizza') {
            logs.push({
                type: 'structured',
                sender: 'PizzaBot',
                message: `ACK: ORDER_ID_${Math.floor(Math.random() * 1000)} | ${payload.params.size} ${payload.params.topping}`,
                status: 'success'
            });
        } else {
            throw new Error("Invalid Action Schema");
        }
    } catch (e: any) {
        logs.push({
            type: 'structured',
            sender: 'PizzaBot',
            message: "Protocol Mismatch: Dropped packet.",
            status: 'failure',
            error: e.message
        });
    }

    return logs;
}
